--Cau 1

CREATE DATABASE QLHANG
GO
USE QLHANG
GO

CREATE TABLE VATTU(
    MAVT varchar(10) PRIMARY KEY, 
    TENVT nvarchar(50),
    DVTINH nvarchar(50),
    SLCON INT
);

CREATE TABLE HDBAN(
    MAHD varchar(10) PRIMARY KEY, 
    NGAYXUAT DATE,
    HOTENKHACH nvarchar(50)
);

CREATE TABLE HANGXUAT(
    MAHD varchar(10),
    MAVT varchar(10),
    DONGIA INT,
    SLBAN INT,
    CONSTRAINT HANGXUAT_PK PRIMARY KEY (MAHD, MAVT)
);

ALTER TABLE HANGXUAT ADD CONSTRAINT FK_HANGXUAT_HDBAN
FOREIGN KEY (MAHD) REFERENCES HDBAN (MAHD);
ALTER TABLE HANGXUAT ADD CONSTRAINT FK_HANGXUAT_VATTU
FOREIGN KEY (MAVT) REFERENCES VATTU (MAVT);

INSERT INTO VATTU VALUES
('VT01', 'NGOI', 'VIEN', 10000),
('VT02', 'CAT', 'BAO', 4000);

INSERT INTO HDBAN VALUES
('HD01', '2022-10-22', 'NGUYEN VAN A'),
('HD02', '2022-10-12', 'TRAN VAN B');

INSERT INTO HANGXUAT VALUES
('HD01', 'VT01', 8000, 500),
('HD01', 'VT02', 38000, 30),
('HD02', 'VT01', 8200, 120),
('HD02', 'VT02', 40000, 50);


--CAu 2

SELECT TOP 1
MAHD, SUM(SLBAN * DONGIA) AS N'Tổng Tiền'
FROM HANGXUAT
GROUP BY MAHD
ORDER BY SUM(SLBAN * DONGIA) Desc;

--Cau 3

CREATE FUNCTION func3 
   ( @mahd varchar(10) )
RETURNS TABLE
AS
RETURN
    SELECT 
        HX.MAHD,
        HD.NGAYXUAT,
        HX.MAVT,
        HX.DONGIA,
        HX.SLBAN,  
        CASE
            WHEN DATEPART(WEEKDAY, HD.NGAYXUAT) = 0 THEN N'Thứ hai'            
            WHEN DATEPART(WEEKDAY, HD.NGAYXUAT) = 1 THEN N'Thứ ba'
            WHEN DATEPART(WEEKDAY, HD.NGAYXUAT) = 2 THEN N'Thứ tư'
            WHEN DATEPART(WEEKDAY, HD.NGAYXUAT) = 3 THEN N'Thứ năm'
            WHEN DATEPART(WEEKDAY, HD.NGAYXUAT) = 4 THEN N'Thứ sáu'
            WHEN DATEPART(WEEKDAY, HD.NGAYXUAT) = 5 THEN N'Thứ bảy'
            ELSE N'Chủ nhật'
        END AS NGAYTHU
    FROM HANGXUAT HX
    INNER JOIN HDBAN HD ON HX.MAHD = HD.MAHD
    WHERE HX.MAHD = @mahd;

select * from func3('HD01')

--Cau 4

CREATE PROCEDURE p4 
@thang int, @nam int 
AS
SELECT 
SUM(SLBAN * DONGIA)
FROM HANGXUAT HX
INNER JOIN HDBAN HD ON HX.MAHD = HD.MAHD
where MONTH(HD.NGAYXUAT) = @THANG AND YEAR(HD.NGAYXUAT) = @NAM;